name: DocFX
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: nikeee/docfx-action@v1.0.0
        name: docfx-action
        with:
          args: Docs/docfx.json

      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: Docs/_site.nosync
          GH_PAT: ${{ secrets.GH_PAT }}
